In [1]:
#This is the beginnings of making a script that can take a general dataset
#Containing data on whether an individual in a specific department has filled out the 'About me' Section
# And/Or has created an avatar
import numpy as np
import pandas as pd
import csv

In [2]:
data_path = r"/Users/Owner/Documents/Work_transfer/Data/GCconnex/"

In [3]:
df1 = pd.read_csv(data_path+'gcconnex_user_about_icon.csv')

In [4]:
#Here we will have to insert the code to group people by a specific column
#That contains the department that they're in
#The current data just contains everybody

In [5]:
#Renaming the About me Icon column, remembering that 55 = About me and 73 = Prof Pic
#This part will have to be altered to account for the department column when the right dataset it in
df1.columns = ['Indicator', 'Content Icon', 'Owner GUID', 'Time Created', 'Last Updated']
df1 = df1.drop('Content Icon', 1)
df1 = df1.drop('Time Created', 1)
df1 = df1.drop('Last Updated', 1)
df1 = df1[['Owner GUID', 'Indicator']]

In [6]:
#Splitting the Dataset into two Dataframes and removing duplicate entries
#If somebody edited their about me profile multiple times they will appear multiple times
df2 = df1.loc[df1['Indicator'] == 73]
df1 = df1.loc[df1['Indicator'] == 55]
df2.drop_duplicates(inplace=True)
df1.drop_duplicates(inplace=True)

In [7]:
#Merging the two dataframes into one single dataframe containing telling whether that individual
#Has filled uploaded an avatar or filled out the "about me" section
df = pd.merge(df1, df2, on='Owner GUID', how='outer')
df.columns = ['Owner GUID', 'About me', 'Avatar']

In [8]:
df.set_index(df['Owner GUID'], inplace=True)
df = df.drop('Owner GUID', 1)

In [9]:
df['Both'] = df['About me'] + df['Avatar']

In [10]:
def f(x):
    if x == 128:
        return 'Y'
    else:
        return 'N'

def g(x):
    if x == 55:
        return 'Y'
    else:
        return 'N'
    
def h(x):
    if x == 73:
        return 'Y'
    else:
        return 'N'

df['Both'] = df['Both'].apply(f)
df['About me'] = df['About me'].apply(g)
df['Avatar'] = df['Avatar'].apply(h)

In [11]:
df

           About me Avatar Both
Owner GUID
22                Y      Y    Y
363               Y      N    N
224               Y      Y    Y
460               Y      Y    Y
70                Y      Y    Y
106               Y      Y    Y
537               Y      Y    Y
1110              Y      Y    Y
1420              Y      Y    Y
1217              Y      Y    Y
1227              Y      Y    Y
1404              Y      Y    Y
1741              Y      Y    Y
775               Y      N    N
669               Y      Y    Y
2233              Y      Y    Y
2269              Y      Y    Y
605               Y      N    N
2203              Y      Y    Y
2352              Y      Y    Y
2213              Y      Y    Y
2289              Y      Y    Y
2532              Y      N    N
2431              Y      Y    Y
2614              Y      N    N
2445              Y      N    N
2679              Y      Y    Y
2299              Y      Y    Y
2693              Y      N    N
2793              Y      Y    Y
...             ...    ...  ...
13049622          N      Y    N
13080308          N      Y    N
3221126           N      Y    N
11773954          N      Y    N
13081537          N      Y    N
864582            N      Y    N
13080394          N      Y    N
7638544           N      Y    N
6350284           N      Y    N
1348450           N      Y    N
157326            N      Y    N
10645708          N      Y    N
13035766          N      Y    N
1364266           N      Y    N
157934            N      Y    N
5987384           N      Y    N
2134554           N      Y    N
3499387           N      Y    N
13108836          N      Y    N
13108852          N      Y    N
1792952           N      Y    N
7172951           N      Y    N
12948479          N      Y    N
11746757          N      Y    N
13109973          N      Y    N
5337922           N      Y    N
11312866          N      Y    N
13142748          N      Y    N
10151552          N      Y    N
419041            N      Y    N

[16200 rows x 3 columns]

In [12]:
df.to_csv(data_path+'About me Avatar Stats.csv')